name: TURF_TOWN_
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:

  sdk: ^3.9.2

#  sdk: '>=3.7.2 <4.0.0' # Good practice to use a version range


# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  objectbox: ^5.0.1
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  bluetooth_classic: ^0.0.4
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  objectbox_generator: ^5.0.1
  build_runner: ^2.10.1
  flutter_test:
  
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  flutter_lints: ^6.0.0

# ---

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/page1.png
    - assets/images/page2.png
    - assets/images/page3.png
    - assets/images/cri_slider.png
    - assets/images/foot_slider.png
    - assets/images/badminton_slider.png
    - assets/images/apple.svg
    - assets/images/ix_support.svg
    - assets/images/Group-1.svg
    - assets/images/picon_on.svg
    - assets/images/Rectangle 4.svg
    - assets/images/mdi_cricket.svg
    - assets/images/mdi_plus-circle-outline.svg
    - assets/images/Group.svg
    - assets/images/ix_support.svg
    - assets/images/Vector.svg
    - assets/images/Rectangle 4.svg
    - assets/images/picon_on.svg
    - assets/images/mdi_cricket.svg
    - assets/images/cricket_ground_1.png.jpg
    - assets/images/cricket_ground_2.png.jpg
    - assets/images/cricket_ground_3.png.jpg
    - assets/images/cricket_ground_4.png.jpg
    - assets/images/cricket_ground_5.png.png
    - assets/images/cricket_ground_6.png.png
    - assets/images/cricket_ground_7.png.png
    - assets/images/cricket_ground_8.png.png
    - assets/images/cricket_ground_9.png.png
    - assets/images/cricket_ground_10.png.jpeg
    - assets/images/filled.svg
    - assets/images/book.svg
    - assets/images/fluent.svg
    - assets/images/Vec.svg
    - assets/images/spanner.svg
    - assets/images/logout.svg
    - assets/images/ground.webp
    - assets/images/stumps.jpg
    - assets/images/megaphone.png
    - assets/images/icons/logo2.avif
    - assets/images/costumer.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

